
<DetailsScreen>:
    id: details
    DetailsScreenCanvas:
        FloatLayout:
            MDTopAppBar:
                title: "App Details"
                left_action_items: [["doghouse.png", lambda x: app.go_home()]]
                pos_hint: {"top": 1}
                FloatLayout:
            Image:
                source: 'paragraphppp.jpg'
                allow_stretch: True
                keep_ratio: True
                size_hint_y: None
                size_hint_x: None
                width: self.parent.width
                height: self.parent.width/self.image_ratio
                pos_hint: {"center_x":0.5, "center_y":0.4}
            Image:
                source: 'cat2.jpg'
                allow_stretch: True
                keep_ratio: True
                size_hint_y: None
                size_hint_x: None
                width: self.parent.width
                height: self.parent.width/self.image_ratio
                pos_hint: {"center_x":0.5, "center_y":0.8}




