
<DetailsScreen>:
    id: details
    DetailsScreenCanvas:
        FloatLayout:
            MDTopAppBar:
                title: "Post Details"
                left_action_items: [["home", lambda x: app.go_home()]]
                pos_hint: {"top": 1}
FloatLayout:
    Button:
        text: "We Will"
        pos: 50, 10
        size_hint: .1, .2
    Button:
        text: "Wee Wiill"
        pos: 200, 200
        size_hint: .4, .2

    Button:
        text: "ROCK YOU!!"
        pos_hint: {'x': .3, 'y': .6}
        size_hint: .5, .2

if __name__ == '__main__':
    PurePawPrintsApp().run()