#:kivy 2.3


<PostsPageScreen>:
    id: posts
    PostsPageScreenCanvas:
        FloatLayout:
            MDTopAppBar:
                title: "Posts - Leave a Print   "
                left_action_items: [["doghouse.png", lambda x: app.go_home()]]
                pos_hint: {"top": 1}

            MDGridLayout:
                cols: 1  # 🔹  columns
                rows: 6  # 🔹  rows
                spacing: "200dp"
                padding: "10dp"
                size_hint: 0.5, 0.5
                pos_hint: {"center_x": 0.5, "center_y": 0.45}

                # 🔹 Hobby 1
                BoxLayout:
                    orientation: "vertical"
                    spacing: "4dp"
                    Image:
                        source: "post1.png"
                        size_hint_y: None
                        height: self.width
                        allow_stretch: True
                        keep_ratio: True

                # 🔹 Hobby 2
                BoxLayout:
                    orientation: "vertical"
                    spacing: "4dp"
                    #- i like ice cream
                    Image:
                        source: "post2.png"
                        size_hint_y: None
                        height: self.width
                        allow_stretch: True
                        keep_ratio: True

                # 🔹 Hobby 3
                BoxLayout:
                    orientation: "vertical"
                    spacing: "4dp"
                    Image:
                        source: "post3.png"
                        size_hint_y: None
                        height: self.width
                        allow_stretch: True
                        keep_ratio: True

                # 🔹 Hobby 4
                BoxLayout:
                    orientation: "vertical"
                    spacing: "4dp"
                    Image:
                        source: "post4.png"
                        size_hint_y: None
                        height: self.width
                        allow_stretch: True
                        keep_ratio: True






<FavoritesScreen>:
    id: favorites
    FavoritesScreenCanvas:
        FloatLayout:
            MDTopAppBar:
                title: "My Favorites"
                left_action_items: [["home", lambda x: app.go_home()]]
                pos_hint: {"top": 1}
