#kivy.space2.3
<HomeScreen>:
    id: home
    HomeScreenCanvas:
        FloatLayout:
            Image:
                source: 'pppbanner.png'
                allow_stretch: True
                keep_ratio: True
                size_hint_y: None
                size_hint_x: None
                width: self.parent.width
                height: self.parent.width/self.image_ratio
                pos_hint: {"center_x":0.5, "center_y":0.91}
            MDLabel:
                adaptive_size: True
                pos_hint: {"center_x":0.5, "center_y":0.755}
                text: "Pure Paw Prints"
                padding: "4dp", "4dp"
                font_style: "H3"
            Image:
                source: 'pppapp.png'
                allow_stretch: True
                keep_ratio: True
                size_hint_y: 0.2
                size_hint_x: 0.2
                width: self.parent.width
                height: self.parent.width/self.image_ratio
                pos_hint: {"center_x":0.5, "center_y":0.84}
            MDRectangleFlatButton:
                adaptive_size: True
                pos_hint: {"center_x":0.5, "center_y":0.45}
                text: "Shelters"
                font_size: "35sp"
                on_press: app.root.current = 'ShelterScreen'

            MDRectangleFlatButton:
                adaptive_size: True
                pos_hint: {"center_x":0.5, "center_y":0.55}
                text: "Posts"
                font_size: "35sp"
                on_press: app.root.current = 'posts'

            MDRectangleFlatButton:
                adaptive_size: True
                pos_hint: {"center_x":0.5, "center_y":0.65}
                text: "Details"
                font_size: "35sp"
                on_press: app.root.current = 'details'
