#:kivy 2.3
<SheltersScreen>:
    id: shelters
    SheltersScreenCanvas:
        FloatLayout:
            MDTopAppBar:
                title: "Shelters"
                left_action_items: [["doghouse.png", lambda x: app.go_home()]]
                pos_hint: {"top": 1}
            Image:
                source: "map.jpg"
                size_hint_y: None
                height: self.width
                allow_stretch: True
                keep_ratio: True
                pos_hint: {"top": 0.8}
            MDLabel:
                text: "Maps"
                halign: "center"
                size_hint_y: None
                height: "20dp"
